version: "3.7"
services:
  mysql:
    image: mysql:8.0.31-debian
    container_name: mysql-8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8088:3306
    volumes:
      - 'localmysql:/var/lib/mysql'
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  localmysql:
    external: true
