version: "3.7"
services:
  mysql:
    image: mysql:5.7.40-debian
    container_name: mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - 'localmysql:/var/lib/mysql'
    networks:
      - local

networks:
  localmysql:
    driver: local
  local:
    driver: local